apiVersion: v1
kind: Service
metadata:
  name: ts4u-homecare
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ts4u-homecare
  type: NodePort
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
